//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoId { get; set; }
        public string Cedula { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int Estado { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
