//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RolId { get; set; }
        public string Nombre { get; set; }
        public string Nota { get; set; }
        public int Enabled { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
