//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccione
    {
        public int TransacId { get; set; }
        public int ClienteId { get; set; }
        public int CuentaId { get; set; }
        public Nullable<int> TUsuarioCuenta { get; set; }
        public string TUsuarioCedula { get; set; }
        public string Notas { get; set; }
        public int TipoTransacId { get; set; }
        public int TUsuarioBancoId { get; set; }
        public Nullable<int> TipoMonedaId { get; set; }
        public Nullable<double> Debito { get; set; }
        public Nullable<double> Credito { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string NoAprobacion { get; set; }
        public int TransaccionCompletada { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual TipoTransaccione TipoTransaccione { get; set; }
    }
}
