//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://LabProg.org/")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        private System.DateTime Fecha_NacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Fecha_Nacimiento {
            get {
                return this.Fecha_NacimientoField;
            }
            set {
                if ((this.Fecha_NacimientoField.Equals(value) != true)) {
                    this.Fecha_NacimientoField = value;
                    this.RaisePropertyChanged("Fecha_Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dosis", Namespace="http://LabProg.org/")]
    [System.SerializableAttribute()]
    public partial class Dosis : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cedula_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Matricula_CentroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_CentroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        private int Fase_VacunacionField;
        
        private int SecuenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cedula_Usuario {
            get {
                return this.Cedula_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Cedula_UsuarioField, value) != true)) {
                    this.Cedula_UsuarioField = value;
                    this.RaisePropertyChanged("Cedula_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Matricula_Centro {
            get {
                return this.Matricula_CentroField;
            }
            set {
                if ((object.ReferenceEquals(this.Matricula_CentroField, value) != true)) {
                    this.Matricula_CentroField = value;
                    this.RaisePropertyChanged("Matricula_Centro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre_Centro {
            get {
                return this.Nombre_CentroField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_CentroField, value) != true)) {
                    this.Nombre_CentroField = value;
                    this.RaisePropertyChanged("Nombre_Centro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Fase_Vacunacion {
            get {
                return this.Fase_VacunacionField;
            }
            set {
                if ((this.Fase_VacunacionField.Equals(value) != true)) {
                    this.Fase_VacunacionField = value;
                    this.RaisePropertyChanged("Fase_Vacunacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://LabProg.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://LabProg.org/", ConfigurationName="WebService.MyWebServicesSoap")]
    public interface MyWebServicesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://LabProg.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://LabProg.org/HelloWorld", ReplyAction="*")]
        Dashboard.WebService.HelloWorldResponse HelloWorld(Dashboard.WebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://LabProg.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WebService.HelloWorldResponse> HelloWorldAsync(Dashboard.WebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name paciente from namespace http://LabProg.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://LabProg.org/Registro", ReplyAction="*")]
        Dashboard.WebService.RegistroResponse Registro(Dashboard.WebService.RegistroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://LabProg.org/Registro", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WebService.RegistroResponse> RegistroAsync(Dashboard.WebService.RegistroRequest request);
        
        // CODEGEN: Generating message contract since element name cedula from namespace http://LabProg.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://LabProg.org/GetDataPaciente", ReplyAction="*")]
        Dashboard.WebService.GetDataPacienteResponse GetDataPaciente(Dashboard.WebService.GetDataPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://LabProg.org/GetDataPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<Dashboard.WebService.GetDataPacienteResponse> GetDataPacienteAsync(Dashboard.WebService.GetDataPacienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://LabProg.org/", Order=0)]
        public Dashboard.WebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Dashboard.WebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://LabProg.org/", Order=0)]
        public Dashboard.WebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Dashboard.WebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LabProg.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registro", Namespace="http://LabProg.org/", Order=0)]
        public Dashboard.WebService.RegistroRequestBody Body;
        
        public RegistroRequest() {
        }
        
        public RegistroRequest(Dashboard.WebService.RegistroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LabProg.org/")]
    public partial class RegistroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WebService.Paciente paciente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Dashboard.WebService.Dosis dosis;
        
        public RegistroRequestBody() {
        }
        
        public RegistroRequestBody(Dashboard.WebService.Paciente paciente, Dashboard.WebService.Dosis dosis) {
            this.paciente = paciente;
            this.dosis = dosis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroResponse", Namespace="http://LabProg.org/", Order=0)]
        public Dashboard.WebService.RegistroResponseBody Body;
        
        public RegistroResponse() {
        }
        
        public RegistroResponse(Dashboard.WebService.RegistroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LabProg.org/")]
    public partial class RegistroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dashboard.WebService.Respuesta RegistroResult;
        
        public RegistroResponseBody() {
        }
        
        public RegistroResponseBody(Dashboard.WebService.Respuesta RegistroResult) {
            this.RegistroResult = RegistroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPaciente", Namespace="http://LabProg.org/", Order=0)]
        public Dashboard.WebService.GetDataPacienteRequestBody Body;
        
        public GetDataPacienteRequest() {
        }
        
        public GetDataPacienteRequest(Dashboard.WebService.GetDataPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LabProg.org/")]
    public partial class GetDataPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public GetDataPacienteRequestBody() {
        }
        
        public GetDataPacienteRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPacienteResponse", Namespace="http://LabProg.org/", Order=0)]
        public Dashboard.WebService.GetDataPacienteResponseBody Body;
        
        public GetDataPacienteResponse() {
        }
        
        public GetDataPacienteResponse(Dashboard.WebService.GetDataPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LabProg.org/")]
    public partial class GetDataPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataPacienteResult;
        
        public GetDataPacienteResponseBody() {
        }
        
        public GetDataPacienteResponseBody(string GetDataPacienteResult) {
            this.GetDataPacienteResult = GetDataPacienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServicesSoapChannel : Dashboard.WebService.MyWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServicesSoapClient : System.ServiceModel.ClientBase<Dashboard.WebService.MyWebServicesSoap>, Dashboard.WebService.MyWebServicesSoap {
        
        public MyWebServicesSoapClient() {
        }
        
        public MyWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WebService.HelloWorldResponse Dashboard.WebService.MyWebServicesSoap.HelloWorld(Dashboard.WebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Dashboard.WebService.HelloWorldRequest inValue = new Dashboard.WebService.HelloWorldRequest();
            inValue.Body = new Dashboard.WebService.HelloWorldRequestBody();
            Dashboard.WebService.HelloWorldResponse retVal = ((Dashboard.WebService.MyWebServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WebService.HelloWorldResponse> Dashboard.WebService.MyWebServicesSoap.HelloWorldAsync(Dashboard.WebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WebService.HelloWorldResponse> HelloWorldAsync() {
            Dashboard.WebService.HelloWorldRequest inValue = new Dashboard.WebService.HelloWorldRequest();
            inValue.Body = new Dashboard.WebService.HelloWorldRequestBody();
            return ((Dashboard.WebService.MyWebServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WebService.RegistroResponse Dashboard.WebService.MyWebServicesSoap.Registro(Dashboard.WebService.RegistroRequest request) {
            return base.Channel.Registro(request);
        }
        
        public Dashboard.WebService.Respuesta Registro(Dashboard.WebService.Paciente paciente, Dashboard.WebService.Dosis dosis) {
            Dashboard.WebService.RegistroRequest inValue = new Dashboard.WebService.RegistroRequest();
            inValue.Body = new Dashboard.WebService.RegistroRequestBody();
            inValue.Body.paciente = paciente;
            inValue.Body.dosis = dosis;
            Dashboard.WebService.RegistroResponse retVal = ((Dashboard.WebService.MyWebServicesSoap)(this)).Registro(inValue);
            return retVal.Body.RegistroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WebService.RegistroResponse> Dashboard.WebService.MyWebServicesSoap.RegistroAsync(Dashboard.WebService.RegistroRequest request) {
            return base.Channel.RegistroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WebService.RegistroResponse> RegistroAsync(Dashboard.WebService.Paciente paciente, Dashboard.WebService.Dosis dosis) {
            Dashboard.WebService.RegistroRequest inValue = new Dashboard.WebService.RegistroRequest();
            inValue.Body = new Dashboard.WebService.RegistroRequestBody();
            inValue.Body.paciente = paciente;
            inValue.Body.dosis = dosis;
            return ((Dashboard.WebService.MyWebServicesSoap)(this)).RegistroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dashboard.WebService.GetDataPacienteResponse Dashboard.WebService.MyWebServicesSoap.GetDataPaciente(Dashboard.WebService.GetDataPacienteRequest request) {
            return base.Channel.GetDataPaciente(request);
        }
        
        public string GetDataPaciente(string cedula) {
            Dashboard.WebService.GetDataPacienteRequest inValue = new Dashboard.WebService.GetDataPacienteRequest();
            inValue.Body = new Dashboard.WebService.GetDataPacienteRequestBody();
            inValue.Body.cedula = cedula;
            Dashboard.WebService.GetDataPacienteResponse retVal = ((Dashboard.WebService.MyWebServicesSoap)(this)).GetDataPaciente(inValue);
            return retVal.Body.GetDataPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dashboard.WebService.GetDataPacienteResponse> Dashboard.WebService.MyWebServicesSoap.GetDataPacienteAsync(Dashboard.WebService.GetDataPacienteRequest request) {
            return base.Channel.GetDataPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dashboard.WebService.GetDataPacienteResponse> GetDataPacienteAsync(string cedula) {
            Dashboard.WebService.GetDataPacienteRequest inValue = new Dashboard.WebService.GetDataPacienteRequest();
            inValue.Body = new Dashboard.WebService.GetDataPacienteRequestBody();
            inValue.Body.cedula = cedula;
            return ((Dashboard.WebService.MyWebServicesSoap)(this)).GetDataPacienteAsync(inValue);
        }
    }
}
